plataforma/urls.py
from django.urls import path

from . import views

app_name = 'plataforma'

urlpatterns = [
    path('', views.index, name='index'),
    path('contato/', views.contato, name='contato'),
    path('produto/', views.produto, name='produto'),

]

product_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('plataforma.urls'))
]

plataforma/models.py
from django.db import models

# Create your models here.

plataforma/forms.py
from django import forms


class ContatoForm(forms.Form):
    nome = forms.CharField(label='Nome', max_length=100)
    email = forms.EmailField(label='E-mail', max_length=100)
    assunto = forms.CharField(label='Assunto', max_length=120)
    mensagem = forms.CharField(label='Mensagem', widget=forms.Textarea())

plataforma/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render

from plataforma.forms import ContatoForm


def index(request):
    return render(request, 'plataforma/index.html')


def contato(request):
    form = ContatoForm(
        request.POST or None
    )

    if str(request.method) == 'POST':
        print(f'meta {request.META}')
        if form.is_valid():
            form.clean()
            form = ContatoForm()

            messages.success(request, 'E-mail enviado com sucesso')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            messages.error(request, 'Erro ao tentar enviar E-mail')

    context = {
        'form': form
    }
    return render(request, 'plataforma/contato.html', context)


def produto(request):
    return render(request, 'plataforma/produto.html')

plataforma/templates/plataforma/contato.html
{% extends 'global/base.html' %}
{% load django_bootstrap5 %}

{% block head %}
    <title>Contato</title>
    {% bootstrap_css %}
{% endblock head %}


{% block body %}
<div class="container">
    <h1>Contato</h1>

    {% bootstrap_messages %}

    <form action="{% url 'plataforma:contato' %}" method="post" class="form" autocomplete="off">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button "Enviar Mensagem" button_type="submit" button_class="btn-primary" %}
    </form>
</div>
    {% bootstrap_javascript %}
{% endblock body %}

plataforma/templates/plataforma/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>

</body>
</html>

plataforma/templates/plataforma/produtos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Produtos</title>
</head>
<body>

</body>
</html>

templates/global/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% block head %}
    {% endblock head %}
</head>
<body>

    {% block body %}
    {% endblock body %}

</body>
</html>